"""empty message

Revision ID: 34f0bf4c2f03
Revises: 1f6710a311ee
Create Date: 2022-06-08 14:26:16.806692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f0bf4c2f03'
down_revision = '1f6710a311ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('video_url', sa.String(length=255), nullable=False))
    op.add_column('videos', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_column('videos', 's3_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('s3_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('videos', 'image_url')
    op.drop_column('videos', 'video_url')
    # ### end Alembic commands ###
