"""empty message

Revision ID: 1f6710a311ee
Revises: 792a095f0def
Create Date: 2022-05-31 13:46:39.896404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6710a311ee'
down_revision = '792a095f0def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('s3_url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 's3_url')
    # ### end Alembic commands ###
