"""empty message

Revision ID: 792a095f0def
Revises: a593b78d2c2b
Create Date: 2022-05-17 15:57:29.918957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792a095f0def'
down_revision = 'a593b78d2c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=30), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=30), nullable=False))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
